language: android
jdk: oraclejdk7

env:
  matrix:
    - ANDROID_TARGET=android-22  ANDROID_ABI=armeabi-v7a


android:
  components:
    # The BuildTools version used by your project
    - build-tools-23.0.1

    # The SDK version used to compile your project
    - android-17

script:
    - echo "Travis branch is $TRAVIS_BRANCH"
    - echo "Travis branch is in pull request $TRAVIS_PULL+REQUEST"
    - ./gradlew aR
